### ISSUE TITLE
does not work with pydantic 2.5.2

### ISSUE THREAD

**Issue by white-hat** [imryche/blockkit#99]
When `blockkit` is used with the latest version of pydantic, I get errors like

```
AttributeError: 'StaticSelect' object has no attribute 'get'
```

This is caused by model validators not checking if passed argument is actually a dictionary

```python
    @model_validator(mode="before")
    def _validate_values(cls, values: Dict) -> Dict:
        # I added these 2 lines to fix the issue, but I'm not sure if I'm breaking the validation process here
        if not isinstance(values, dict):
            return values
        initial_options = values.get("initial_options")
```

**Comment by lookforward-github** [comment]
Faced the same issue with `TimePicker` and `MultiUsersSelect`. Forced reinstallation of `pydantic 2.3.0` helps.

```
pip install --force-reinstall -v "pydantic==2.3.0"
```

**Comment by imryche** [comment]
Hey, thanks for highlighting the issue. I've fixed the Pydantic compatibility issues in the latest `1.6.2` release. Please go ahead and try it.
